"""
# Prepares high-entailment but incorrect QA predictions for manual qualitative error analysis by normalizing the cases and generating CSV, Markdown, annotation, and summary reports.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any

DEFAULT_INPUT_PATH = Path(
    "outputs/analysis/question_aware_verifier/high_entailment_incorrect.jsonl"
)


DEFAULT_OUTPUT_DIRECTORY = Path("outputs/analysis/high_entailment_investigation")

# QUESTION_FIELDS -> The input question asked to the QA model
QUESTION_FIELDS = (
    "question",
    "query",
    "input_question"
)


# PREDICTION_FIELDS -> The answer predicted/generated by the QA model.
PREDICTION_FIELDS = (
    "predicted_answer",
    "prediction_text",
    "prediction_answer",
    "prediction",
    "model_answer",
    "generated_answer",
    "answer"
)


# REFERENCE_FIELDS -> The correct/gold/reference answer(s) used to evaluate the prediction.
REFERENCE_FIELDS = (
    "reference_answers",
    "gold_answers",
    "accepted_answers",
    "references",
    "reference_answer",
    "gold_answer",
    "target_answer",
    "ground_truth",
    "answers",
    "answer_texts",
    "gold",
    "annotations",
    "targets",
    "labels"
)


# CONFIDENCE_FIELDS -> How confident the QA model is that its predicted answer is correct.
CONFIDENCE_FIELDS = (
    "confidence",
    "calibrated_confidence",
    "temperature_scaled_confidence",
    "qa_calibrated_confidence",
    "qa_confidence",
    "prediction_confidence",
    "max_probability",
    "probability"
)


# ENTAILMENT_FIELDS -> Probability/score that the evidence supports the generated claim.
ENTAILMENT_FIELDS = (
    "entailment_probability",
    "qa_entailment_probability",
    "question_aware_entailment_probability",
    "question_aware_semantic_score",
    "qa_semantic_score"
)


# CONTRADICTION_FIELDS -> Probability that the evidence contradicts the generated claim.
CONTRADICTION_FIELDS = (
    "contradiction_probability",
    "qa_contradiction_probability",
    "question_aware_contradiction_probability",
)


# NEUTRAL_FIELDS -> Probability that the evidence neither supports nor contradicts the claim.
NEUTRAL_FIELDS = (
    "neutral_probability",
    "qa_neutral_probability",
    "question_aware_neutral_probability"
)


# LABEL_FIELDS -> Final semantic/NLI label, usually ENTAILMENT, CONTRADICTION, or NEUTRAL.
LABEL_FIELDS = (
    "nli_label",
    "qa_nli_label",
    "question_aware_nli_label",
    "qa_verification_label",
    "semantic_label"
)


# CLAIM_FIELDS -> A statement created from the question and predicted answer so that it can be verified by NLI.
CLAIM_FIELDS = (
    "claim",
    "qa_claim",
    "generated_claim",
    "question_aware_claim"
)


# EVIDENCE_FIELDS -> The context/passage retrieved or provided to support or verify the prediction.
EVIDENCE_FIELDS = (
    "evidence",
    "hybrid_evidence",
    "retrieved_evidence",
    "evidence_text",
    "context",
    "passage",
    "supporting_evidence"
)


# CLAIM_VALIDITY_FIELDS -> Whether the generated claim is valid and suitable for semantic verification.
CLAIM_VALIDITY_FIELDS = (
    "claim_valid",
    "qa_claim_valid",
    "question_aware_claim_valid"
)


# INVALID_REASON_FIELDS -> Reasons explaining why a generated claim was considered invalid.
INVALID_REASON_FIELDS = (
    "invalid_claim_reasons",
    "qa_invalid_claim_reasons",
    "claim_invalid_reasons",
    "qa_claim_invalid_reasons"
)


# RETRIEVER_SCORE_FIELDS -> Score showing how relevant the retrieved evidence is to the question/query.
RETRIEVER_SCORE_FIELDS = (
    "retriever_score",
    "retrieval_score",
    "hybrid_retrieval_score",
    "dense_score",
    "reranker_score",
    "evidence_score"
)


# SOURCE_FIELDS -> Information identifying where the evidence came from, such as a document or passage ID.
SOURCE_FIELDS = (
    "source",
    "document_id",
    "doc_id",
    "passage_id",
    "evidence_source"
)


# CORRECTNESS_FIELDS -> Whether the QA prediction matches the gold/reference answer.
CORRECTNESS_FIELDS = (
    "correct",
    "is_correct",
    "exact_match",
    "em",
    "prediction_correct",
    "is_exact_match",
    "exact_match_score",
    "em_score",
    "answer_correct",
    "prediction_is_correct",
    "qa_is_correct"
)


# ANSWERABLE_FIELDS -> Whether the question actually has an answer in the provided evidence/context.
ANSWERABLE_FIELDS = (
    "is_answerable",
    "answerable",
    "has_answer"
)

# Defines the columns that will be saved for each investigated error case.
OUTPUT_COLUMNS = (
    "case_id",
    "record_index",
    "question",
    "gold_answers",
    "is_answerable",
    "prediction",
    "correct",
    "confidence",
    "entailment_probability",
    "contradiction_probability",
    "neutral_probability",
    "nli_label",
    "claim",
    "evidence",
    "retriever_score",
    "evidence_source",
    "claim_valid",
    "invalid_claim_reasons"
)


# Extends the output columns with fields used for manual error annotation.
ANNOTATION_COLUMNS = (
    *OUTPUT_COLUMNS,
    "primary_error_category",
    "secondary_error_category",
    "retrieval_relevant",
    "evidence_supports_prediction",
    "claim_preserves_answer",
    "claim_preserves_question_meaning",
    "nli_label_reasonable",
    "gold_annotation_clear",
    "notes"
)


# value -> string -> remove extra spaces/newlines/tabs -> return clean text.
def clean_text(value: Any) -> str:
    if value is None:
        return ""

    return re.sub(r"\s+", " ", str(value)).strip()



# check file exists -> read line by line -> parse JSON -> validate each record -> collect records -> return list.
def load_jsonl(path: str | Path) -> list[dict[str, Any]]:
    input_path = Path(path)

    if not input_path.exists():
        raise FileNotFoundError(f"Input file does not exist: {input_path}")

    records: list[dict[str, Any]] = []

    with input_path.open("r", encoding="utf-8") as input_file:
        for line_number, line in enumerate(input_file, start=1):
            stripped = line.strip()

            if not stripped:
                continue

            try:
                record = json.loads(stripped)
            except json.JSONDecodeError as error:
                raise ValueError(
                    f"Invalid JSON at line {line_number}: {error}"
                ) from error

            if not isinstance(record, dict):
                raise TypeError(f"Line {line_number} must contain a JSON object.")

            records.append(record)

    if not records:
        raise ValueError(f"No records were found in {input_path}")

    return records



# convert path -> create folder -> open file -> write JSON with readable formatting.
def save_json(data: Any, path: str | Path) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as output_file:
        json.dump(
            data,
            output_file,
            indent=2,
            ensure_ascii=False
        )


# create folder -> open CSV file -> define columns -> write header -> write all rows.
def save_csv(
    rows: Sequence[dict[str, Any]],
    path: str | Path,
    fieldnames: Sequence[str]
) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open(
        "w",
        encoding="utf-8",
        newline=""
    ) as output_file:
        writer = csv.DictWriter(
            output_file,
            fieldnames=list(fieldnames),
            extrasaction="ignore"
        )

        writer.writeheader()
        writer.writerows(rows)



# check field names in order -> return first valid value -> otherwise return default.
def get_first_value(
    record: dict[str, Any],
    field_names: Sequence[str],
    default: Any = None
) -> Any:
    for field_name in field_names:
        if field_name in record and record[field_name] is not None:
            return record[field_name]

    return default



# check current dictionary -> search deeper nested structures -> return first matching value -> otherwise None.
def recursive_field_search(
    value: Any,
    field_names: Sequence[str]
) -> Any:
    if isinstance(value, dict):
        for field_name in field_names:
            if field_name in value:
                return value[field_name]

        for nested_value in value.values():
            result = recursive_field_search(
                nested_value,
                field_names
            )

            if result is not None:
                return result

    elif isinstance(value, (list, tuple)):
        for item in value:
            if not isinstance(item, (dict, list, tuple)):
                continue

            result = recursive_field_search(
                item,
                field_names
            )

            if result is not None:
                return result

    return None



# check direct field -> search common nested sections -> search whole record recursively -> return default if nothing is found.
def extract_nested_value(
    record: dict[str, Any],
    field_names: Sequence[str],
    nested_containers: Sequence[str] = (
        "source_record",
        "metadata",
        "verification",
        "semantic_verification",
        "question_aware_verification",
        "retrieval",
        "example",
        "sample",
        "data"
    ),
    default: Any = None
) -> Any:
    direct_value = get_first_value(
        record,
        field_names,
        default=None
    )

    if direct_value is not None:
        return direct_value

    for container_name in nested_containers:
        container = record.get(container_name)

        if not isinstance(container, (dict, list, tuple)):
            continue

        nested_value = recursive_field_search(
            container,
            field_names
        )

        if nested_value is not None:
            return nested_value

    recursive_value = recursive_field_search(
        record,
        field_names
    )

    if recursive_value is not None:
        return recursive_value

    return default



# Recursively extracts reference answers from different data formats, cleans them, removes duplicates, and returns a flat list of strings.
def flatten_references(value: Any) -> list[str]:
    if value is None:
        return []

    if isinstance(value, str):
        cleaned = clean_text(value)
        return [cleaned] if cleaned else []

    if isinstance(value, (int, float, bool)):
        return [clean_text(value)]

    if isinstance(value, dict):
        preferred_text_fields = (
            "text",
            "answer",
            "answers",
            "answer_text",
            "answer_texts",
            "reference_answer",
            "reference_answers",
            "gold_answer",
            "gold_answers",
            "value",
            "label"
        )

        for key in preferred_text_fields:
            if key in value:
                extracted = flatten_references(value[key])

                if extracted:
                    return extracted


        # Annotation-style structures may contain nested answer objects.
        collected: list[str] = []

        for key, nested_value in value.items():
            # Avoid treating offsets, IDs and scores as answers.
            if key.lower() in {
                "answer_start",
                "start",
                "end",
                "offset",
                "offsets",
                "score",
                "probability",
                "id"
            }:
                continue

            if isinstance(
                nested_value,
                (dict, list, tuple)
            ):
                collected.extend(flatten_references(nested_value))

        return list(dict.fromkeys(collected))

    if isinstance(value, (list, tuple, set)):
        references: list[str] = []

        for item in value:
            references.extend(flatten_references(item))

        return list(dict.fromkeys(reference for reference in references if reference))

    return []



# Converts different value formats into a clean single string, joining iterable items with " | ".
def stringify_list(value: Any) -> str:
    if value is None:
        return ""

    if isinstance(value, str):
        return clean_text(value)

    if isinstance(value, dict):
        return json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True
        )

    if isinstance(value, Iterable):
        cleaned = [clean_text(item) for item in value if clean_text(item)]
        return " | ".join(cleaned)

    return clean_text(value)



# Converts common boolean-like values into True or False, or returns None if the value cannot be recognized.
def coerce_boolean(value: Any) -> bool | None:
    if isinstance(value, bool):
        return value

    if isinstance(value, int):
        if value == 1:
            return True
        
        if value == 0:
            return False

    if isinstance(value, float):
        if value == 1.0:
            return True
        
        if value == 0.0:
            return False

    if isinstance(value, str):
        normalized = value.strip().lower()

        if normalized in {
            "true",
            "yes",
            "correct",
            "1",
            "1.0",
            "valid"
        }:
            return True

        if normalized in {
            "false",
            "no",
            "incorrect",
            "0",
            "0.0",
            "invalid"
        }:
            return False

    return None



# Converts a boolean-like value into the strings "true" or "false", or returns an empty string if it cannot be recognized.
def format_boolean(value: Any) -> str:
    boolean = coerce_boolean(value)

    if boolean is True:
        return "true"

    if boolean is False:
        return "false"

    return ""



# Converts a value to a fixed six-decimal numeric string, or returns cleaned text if numeric conversion is not possible.
def format_number(value: Any) -> str:
    if value is None or value == "":
        return ""

    try:
        number = float(value)
    except (TypeError, ValueError):
        return clean_text(value)

    return f"{number:.6f}"



# Converts a raw QA record into one standardized analysis row by extracting, cleaning, formatting, and organizing all important diagnostic fields.
def normalise_record(
    record: dict[str, Any],
    case_id: int
) -> dict[str, Any]:
    references = flatten_references(
        extract_nested_value(
            record,
            REFERENCE_FIELDS,
            default=[]
        )
    )

    is_answerable = coerce_boolean(
        extract_nested_value(
            record,
            ANSWERABLE_FIELDS,
            default=None
        )
    )

    if not references and is_answerable is False:
        gold_answers = "[UNANSWERABLE]"

    else:
        gold_answers = " | ".join(references)

    invalid_reasons = extract_nested_value(
        record,
        INVALID_REASON_FIELDS,
        default=[]
    )

    row = {
        "case_id": case_id,
        "record_index": record.get(
            "index",
            record.get(
                "_analysis_index",
                record.get("record_index", "")
            )
        ),
        "question": clean_text(
            extract_nested_value(
                record,
                QUESTION_FIELDS,
                default=""
            )
        ),
        "gold_answers": gold_answers,
        "is_answerable": (format_boolean(is_answerable)),
        "prediction": clean_text(
            extract_nested_value(
                record,
                PREDICTION_FIELDS,
                default=""
            )
        ),
        "correct": format_boolean(
            extract_nested_value(
                record,
                CORRECTNESS_FIELDS,
                default=False
            )
        ),
        "confidence": format_number(
            extract_nested_value(
                record,
                CONFIDENCE_FIELDS,
                default=None
            )
        ),
        "entailment_probability": format_number(
            extract_nested_value(
                record,
                ENTAILMENT_FIELDS,
                default=None
            )
        ),
        "contradiction_probability": format_number(
            extract_nested_value(
                record,
                CONTRADICTION_FIELDS,
                default=None
            )
        ),
        "neutral_probability": format_number(
            extract_nested_value(
                record,
                NEUTRAL_FIELDS,
                default=None
            )
        ),
        "nli_label": clean_text(
            extract_nested_value(
                record,
                LABEL_FIELDS,
                default=""
            )
        ).upper(),
        "claim": clean_text(
            extract_nested_value(
                record,
                CLAIM_FIELDS,
                default=""
            )
        ),
        "evidence": clean_text(
            extract_nested_value(
                record,
                EVIDENCE_FIELDS,
                default=""
            )
        ),
        "retriever_score": format_number(
            extract_nested_value(
                record,
                RETRIEVER_SCORE_FIELDS,
                default=None
            )
        ),
        "evidence_source": clean_text(
            extract_nested_value(
                record,
                SOURCE_FIELDS,
                default=""
            )
        ),
        "claim_valid": format_boolean(
            extract_nested_value(
                record,
                CLAIM_VALIDITY_FIELDS,
                default=None
            )
        ),
        "invalid_claim_reasons": stringify_list(invalid_reasons)
    }

    return row



# Escapes special Markdown characters so text can be safely displayed inside Markdown tables.
def escape_markdown(value: Any) -> str:
    text = clean_text(value)

    text = text.replace("\\", "\\\\")
    text = text.replace("|", "\\|")
    text = text.replace("\n", "<br>")

    return text



# Shortens text to a maximum number of characters and adds an ellipsis when truncation is needed.
def truncate_text(
    value: str,
    maximum_characters: int
) -> str:
    text = clean_text(value)

    if maximum_characters <= 0:
        return text

    if len(text) <= maximum_characters:
        return text

    return text[: maximum_characters - 1].rstrip() + "…"



# Generates a Markdown report for high-entailment incorrect predictions, showing each case in a readable table with fields for manual error annotation.
def render_markdown(
    rows: Sequence[dict[str, Any]],
    maximum_evidence_characters: int
) -> str:
    lines: list[str] = [
        "# High-Entailment Incorrect Predictions",
        "",
        (
            "These cases were automatically selected because the QA "
            "prediction was incorrect while the question-aware verifier "
            "assigned high entailment. Error categories must be assigned "
            "manually."
        ),
        "",
        "## Annotation categories",
        "",
        "- `RETRIEVAL_ERROR`",
        "- `QA_PREDICTION_ERROR`",
        "- `CLAIM_GENERATION_ERROR`",
        "- `NLI_ERROR`",
        "- `ANNOTATION_AMBIGUITY`",
        "- `EVIDENCE_SUPPORTS_WRONG_ANSWER`",
        "- `MULTIPLE_FAILURES`",
        "- `OTHER`",
        ""
    ]

    for row in rows:
        lines.extend(
            [
                f"## Case {row['case_id']}",
                "",
                "| Field | Value |",
                "|---|---|",
                (f"| Record index | {escape_markdown(row['record_index'])} |"),
                (f"| Question | {escape_markdown(row['question'])} |"),
                (f"| Gold answer(s) | {escape_markdown(row['gold_answers'])} |"),
                (f"| Answerable | {escape_markdown(row['is_answerable'])} |"),
                (f"| Prediction | {escape_markdown(row['prediction'])} |"),
                (f"| Confidence | {escape_markdown(row['confidence'])} |"),
                (
                    "| Entailment probability | "
                    f"{escape_markdown(row['entailment_probability'])} |"
                ),
                (
                    "| Contradiction probability | "
                    f"{escape_markdown(row['contradiction_probability'])} |"
                ),
                (
                    "| Neutral probability | "
                    f"{escape_markdown(row['neutral_probability'])} |"
                ),
                (f"| NLI label | {escape_markdown(row['nli_label'])} |"),
                (f"| Claim | {escape_markdown(row['claim'])} |"),
                (
                    "| Evidence | "
                    f"{escape_markdown(truncate_text(row['evidence'], maximum_evidence_characters))} |"
                ),
                (f"| Retriever score | {escape_markdown(row['retriever_score'])} |"),
                (f"| Evidence source | {escape_markdown(row['evidence_source'])} |"),
                (f"| Claim valid | {escape_markdown(row['claim_valid'])} |"),
                (
                    "| Invalid reasons | "
                    f"{escape_markdown(row['invalid_claim_reasons'])} |"
                ),
                "| Primary error category |  |",
                "| Secondary error category |  |",
                "| Notes |  |",
                ""
            ]
        )

    return "\n".join(lines)



# Builds a compact summary of the investigated cases by counting NLI labels, claim validity, missing fields, and average confidence/entailment scores.
def build_summary(
    rows: Sequence[dict[str, Any]],
    input_path: str | Path
) -> dict[str, Any]:
    label_counts = Counter(row["nli_label"] or "UNKNOWN" for row in rows)

    valid_counts = Counter(row["claim_valid"] or "UNKNOWN" for row in rows)

    missing_fields = Counter()

    fields_to_check = (
        "question",
        "gold_answers",
        "prediction",
        "confidence",
        "entailment_probability",
        "claim",
        "evidence"
    )

    for row in rows:
        for field_name in fields_to_check:
            if not row[field_name]:
                missing_fields[field_name] += 1

    entailment_scores: list[float] = []
    confidence_scores: list[float] = []

    for row in rows:
        if row["entailment_probability"]:
            try:
                entailment_scores.append(float(row["entailment_probability"]))
            except ValueError:
                pass

        if row["confidence"]:
            try:
                confidence_scores.append(float(row["confidence"]))
            except ValueError:
                pass

    return {
        "input_path": str(input_path),
        "total_cases": len(rows),
        "nli_label_counts": dict(label_counts),
        "claim_validity_counts": dict(valid_counts),
        "missing_field_counts": dict(missing_fields),
        "mean_entailment_probability": (
            sum(entailment_scores) / len(entailment_scores)
            if entailment_scores
            else None
        ),
        "mean_confidence": (
            sum(confidence_scores) / len(confidence_scores)
            if confidence_scores
            else None
        ),
        "manual_annotation_categories": [
            "RETRIEVAL_ERROR",
            "QA_PREDICTION_ERROR",
            "CLAIM_GENERATION_ERROR",
            "NLI_ERROR",
            "ANNOTATION_AMBIGUITY",
            "EVIDENCE_SUPPORTS_WRONG_ANSWER",
            "MULTIPLE_FAILURES",
            "OTHER"
        ]
    }



# Runs the full high-entailment error-investigation pipeline by loading cases, normalizing them, generating annotation files and reports, building a summary, and printing the output locations.
def investigate_high_entailment_errors(
    input_path: str | Path,
    output_directory: str | Path,
    maximum_evidence_characters: int
) -> None:
    records = load_jsonl(input_path)

    rows = [
        normalise_record(
            record,
            case_id=index
        )
        for index, record in enumerate(records, start=1)
    ]

    output_path = Path(output_directory)
    output_path.mkdir(parents=True, exist_ok=True)

    save_csv(
        rows,
        output_path / "high_entailment_cases.csv",
        fieldnames=OUTPUT_COLUMNS
    )

    annotation_rows = []

    for row in rows:
        annotation_row = dict(row)

        annotation_row.update(
            {
                "primary_error_category": "",
                "secondary_error_category": "",
                "retrieval_relevant": "",
                "evidence_supports_prediction": "",
                "claim_preserves_answer": "",
                "claim_preserves_question_meaning": "",
                "nli_label_reasonable": "",
                "gold_annotation_clear": "",
                "notes": ""
            }
        )

        annotation_rows.append(annotation_row)

    save_csv(
        annotation_rows,
        output_path / "annotation_template.csv",
        fieldnames=ANNOTATION_COLUMNS
    )

    markdown = render_markdown(
        rows,
        maximum_evidence_characters=maximum_evidence_characters
    )

    with (output_path / "high_entailment_cases.md").open(
        "w", encoding="utf-8"
    ) as markdown_file:
        markdown_file.write(markdown)

    summary = build_summary(
        rows,
        input_path=input_path
    )

    save_json(
        summary,
        output_path / "summary.json"
    )

    print("\n" + "=" * 92)
    print("HIGH-ENTAILMENT ERROR INVESTIGATION")
    print("=" * 92)

    print(f"Input cases: {len(rows)}")

    print("\nNLI labels:")
    for label, count in sorted(summary["nli_label_counts"].items()):
        print(f"  {label:<20} {count}")

    print("\nClaim validity:")
    for validity, count in sorted(summary["claim_validity_counts"].items()):
        print(f"  {validity:<20} {count}")

    print("\nMissing fields:")
    if summary["missing_field_counts"]:
        for field_name, count in sorted(summary["missing_field_counts"].items()):
            print(f"  {field_name:<28} {count}")
    else:
        print("  None")

    print("\n" + "-" * 92)
    print("OUTPUT FILES")
    print("-" * 92)

    for filename in (
        "high_entailment_cases.csv",
        "high_entailment_cases.md",
        "annotation_template.csv",
        "summary.json"
    ):
        print(output_path / filename)


# Converts a command-line value to a non-negative integer and raises an error if the value is below zero.
def non_negative_integer(value: str) -> int:
    number = int(value)

    if number < 0:
        raise argparse.ArgumentTypeError("Value must be zero or greater.")

    return number


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Prepare high-entailment incorrect predictions for "
            "manual qualitative error analysis."
        )
    )

    parser.add_argument(
        "--input",
        default=str(DEFAULT_INPUT_PATH),
        help=("Input JSONL file containing high-entailment incorrect predictions.")
    )

    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIRECTORY),
        help="Directory where analysis files will be written."
    )

    parser.add_argument(
        "--max-evidence-characters",
        type=non_negative_integer,
        default=2500,
        help=(
            "Maximum evidence length in the Markdown report. "
            "Use 0 to disable truncation. CSV output is never truncated."
        )
    )

    return parser.parse_args()


if __name__ == "__main__":
    arguments = parse_arguments()

    investigate_high_entailment_errors(
        input_path=arguments.input,
        output_directory=arguments.output_dir,
        maximum_evidence_characters=(arguments.max_evidence_characters),
    )
